# Generated by Django 2.1.3 on 2019-01-03 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendTime', models.DateField()),
                ('sender', models.CharField(max_length=20)),
                ('messageType', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('begin', models.DateField()),
                ('deadline', models.DateField()),
                ('subjectUrl', models.CharField(max_length=100)),
                ('webpageUrl', models.CharField(max_length=100)),
                ('desc', models.CharField(default='', max_length=250)),
                ('loc', models.CharField(default='', max_length=40)),
                ('keywords', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('isIndexed', models.BooleanField(default=False)),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbworld.Doc')),
            ],
        ),
        migrations.CreateModel(
            name='Wordindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=45)),
                ('_index', models.TextField(null=True)),
            ],
        ),
    ]
